### ISSUE TITLE
Request pool should contain all requests

### ISSUE THREAD

**Issue by bridgetnoelleee** [marcteves/cs191-project#33]

**Comment by bridgetnoelleee** [comment]
Should include the requests of the logged in user

**Comment by marcteves** [comment]
Right now we display all pending_accept requests in the request pool, *excluding* the ones the viewing user requested themselves.

If I understand, this means that we change the behavior to displaying every pending_accept request in the request pool, *including* the ones that the user requested themselves. If that's correct I can start working on this.
